services:
  - type: web
    name: InstantAI
    runtime: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: GEMINI_API_KEY
        sync: false
    pullRequestPreviewsEnabled: true
